spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rocketmq_study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver